
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 2;
const int acc_off_y = 26;
const int acc_off_z = 256;
const float acc_scale_x = 270.536564;
const float acc_scale_y = 304.108274;
const float acc_scale_z = 267.671795;

const int magn_off_x = -46;
const int magn_off_y = 52;
const int magn_off_z = -53;
const float magn_scale_x = 543.644522;
const float magn_scale_y = 488.416554;
const float magn_scale_z = 491.896042;
